### ISSUE TITLE
Setup procedure

### ISSUE THREAD

**Issue by ghost** [SchulzLab/TEPIC#11]
I just followed the documented setup procedure and stumbled across the following shortcomings:
- presence of R3 is not enough, the following non-default packages have to be installed:
  -- cran::evd
  -- bioconductor::biostrings
- the hard-coded call to `R3script` (line 173) in TEPIC.sh is sub-optimal since this may not exist in a clean environment (the default is Rscript for both R2.x and R3.x). It would be advisable to check for (i) existence of `R3script` and, in case of failure, (ii) to check the output of `Rscript --version` for compatibility

The following is a minimal Conda YAML file to install a clean environment for TEPIC:

``` yaml
name: tepic
channels:
    - bioconda
    - r
dependencies:
    - python=2.7.*
    - bedtools=2.26.0
    - r-base=3.3.1
    - bioconductor-biostrings
```

And a small bash script to install the remaining R packages (both seem not to be in the Conda R channels):

``` bash
#!/bin/bash

echo "Downloading packages..."
wget -nd -nH -P ${HOME}/Downloads http://trap.molgen.mpg.de/download/TRAP_R_package/tRap_0.5.tar.gz
wget -nd -nH -P ${HOME}/Downloads https://cran.rstudio.com/src/contrib/evd_2.3-2.tar.gz

EVDPCK=${HOME}/Downloads/evd_2.3-2.tar.gz
TRAPPCK=${HOME}/Downloads/tRap_0.5.tar.gz

source activate tepic && echo "TEPIC environment activated"

R CMD INSTALL ${EVDPCK}

R CMD INSTALL ${TRAPPCK}

source deactivate

exit 0
```

Maybe, you find that useful.
